# Generated by Django 4.1.7 on 2023-03-20 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('ativo', models.BooleanField()),
                ('versao', models.BigIntegerField()),
                ('titulo', models.TextField()),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('tipo_entrega', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'polare"."entrega',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlanoIndividual',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('ativo', models.BooleanField()),
                ('versao', models.BigIntegerField()),
                ('ano_referencia', models.IntegerField()),
                ('carga_horaria', models.IntegerField(blank=True, null=True)),
                ('equipe', models.CharField(blank=True, max_length=255, null=True)),
                ('modelo_trabalho', models.CharField(max_length=255)),
                ('nome', models.CharField(max_length=255)),
                ('siape', models.CharField(max_length=255)),
                ('situacao', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'polare"."plano_individual',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subtarefa',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('ativo', models.BooleanField()),
                ('versao', models.BigIntegerField()),
                ('descricao', models.TextField()),
                ('finalizado', models.BooleanField()),
            ],
            options={
                'db_table': 'polare"."subtarefa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('ativo', models.BooleanField()),
                ('versao', models.BigIntegerField()),
                ('codigo', models.CharField(max_length=255)),
                ('hierarquia_organizacional', models.CharField(max_length=255)),
                ('nome', models.CharField(max_length=255)),
                ('nome_ascii', models.CharField(max_length=255)),
                ('sigla', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'polare"."unidade',
                'managed': False,
            },
        ),
    ]
